### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by kosirm** [Zhibade/maya-vector-displacement-deformer#1]
Hi, I'd like to try this plugin, but I have problems to compile it. I have maya sdk, , Cmake, I installed Visual Studio, everything looks ok, cmake shows no errors, but I can't find .mll file anywhere, just a bunch of cmake files and VS solution files. Could you please compile .mll for Maya 2018.6 Windows ?

**Comment by Zhibade** [comment]
Hello!

Both the .dll and .mll files should be in the build folder along with the other VS debug files. The default path is _/MayaVectorDisplacementDeformer/out/build/x64-Debug_.

I have compiled the plugin for Maya 2018 Update 6 and attached it here. Please make sure that the _VectorDisplacementDeformer.cl_ file is in the same folder as the .mll file (I have also included it in the attached ZIP file).  

Unfortunately I don't have access to Maya 2018 right now, so I am unable to test it. Please let me know if you have any problems.

[MayaVectorDisplacementDeformer_Maya2018-6.zip](https://github.com/Zhibade/maya-vector-displacement-deformer/files/5610672/MayaVectorDisplacementDeformer_Maya2018-6.zip)

**Comment by kosirm** [comment]
Thank you so much! 
Unfortunately I can't load the plugin.
`// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: The specified module could not be found. (MayaVectorDisplacementDeformer) // `
But never mind, I figure out how can I do it without plugin, only with built-in Maya tools...
BR, Milan

**Comment by kosirm** [comment]
Thanks again for your kind help!
BR, Milan
